filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: nginx
      hints.enabled: true
  
processors:
  - add_docker_metadata: ~

setup.kibana.host: ${KIBANA_HOST}

output.elasticsearch:
  hosts: ['${ELASTIC_HOST}']